# Generated by Django 4.1.2 on 2022-10-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
