# Generated by Django 4.1.2 on 2022-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_rename_firs_name_users_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='User first Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='User last Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=20, verbose_name='User password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=120, verbose_name='Username'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='user_data_users',
        ),
    ]
