# Generated by Django 4.1.2 on 2022-10-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_alter_users_first_name_alter_users_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_join',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
