# Generated by Django 4.1.2 on 2022-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_alter_users_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_join',
            field=models.CharField(max_length=100),
        ),
    ]
