# Generated by Django 4.1.2 on 2022-10-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_alter_users_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='User first Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='User last Name'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='user_data_users',
        ),
    ]
