# Generated by Django 4.1.2 on 2022-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_users_file_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title for upload file')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='upload file')),
            ],
        ),
    ]
