# Generated by Django 4.1.2 on 2022-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_uploadfilemodel_delete_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='document',
            field=models.FileField(upload_to='media'),
        ),
    ]
